# Generated by Django 2.1.5 on 2019-05-17 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 17, 19, 1, 333362), verbose_name='published Field'),
        ),
    ]
